### ISSUE TITLE
[REVIEWERS] Docs TS

### ISSUE THREAD

**Issue by manekinekko** [angular/angular-fr#40]
# Docs TS

**Note: before checking a line, make sure that the related PR has been merged and the build is  green.**

- [ ] Docs TS: includes (#3)
- [ ] Docs TS: glossary (#4)
- [ ] Docs TS: cli-quickstart (#5)
- [ ] Docs TS: quickstart (#6)
- [ ] Docs TS: divers (#7)
- [ ] Docs TS: cookbook pt.1 (#8)
- [ ] Docs TS: cookbook pt.2 (#9)
- [ ] Docs TS: cookbook pt.3 (#10)
- [ ] Docs TS: cookbook pt.4 (#11)
- [ ] Docs TS: guide animations (#12)
- [ ] Docs TS: guide architecture (#13)
- [ ] Docs TS: guide attribute-directives (#14)
- [ ] Docs TS: guide component-styles (#15)
- [ ] Docs TS: guide dependency-injection (#16)
- [ ] Docs TS: guide displaying-data (#17)
- [ ] Docs TS: guide forms-deprecated (#18)
- [ ] Docs TS: guide forms (#19)
- [ ] Docs TS: guide hierarchical-dependency-injection (#20)
- [ ] Docs TS: guide divers (#21)
- [ ] Docs TS: guide lifecycle-hooks (#22)
- [ ] Docs TS: guide npm-packages (#23)
- [ ] Docs TS: guide pipes (#24)
- [ ] Docs TS: guide router-deprecated (#25)
- [ ] Docs TS: guide router (#26)
- [ ] Docs TS: guide security (#27)
- [ ] Docs TS: guide server-communication (#28)
- [ ] Docs TS: guide structural-directives (#29)
- [ ] Docs TS: guide style-guide (#30)
- [ ] Docs TS: guide template-syntax (#31)
- [ ] Docs TS: guide upgrade (#32)
- [ ] Docs TS: guide webpack (#33)
- [ ] Docs TS: testing pt1 (#34)
- [ ] Docs TS: testing pt2 (#35)
- [ ] Docs TS: tutorial TOH pt1-2 (#36)
- [ ] Docs TS: tutorial TOH pt3-4 (#37)
- [ ] Docs TS: tutorial TOH pt5 (#38)
- [ ] Docs TS: tutorial TOH pt6 (#39)

**Comment by ctesniere** [comment]
On ne traduit pas les cheatsheets ? https://angular.io/docs/ts/latest/guide/cheatsheet.html

**Comment by manekinekko** [comment]
Oui, je pense.

@naomiblack  tu confirmes ?

**Comment by manekinekko** [comment]
Voici les guidelines à prendre en compte pour les rédacteurs. Evidement, les guidelines sont pour la langue Anglaise, à vous de faire le tri: https://docs.google.com/document/d/1ETcX_38vkR8NkGyKqhWoCnPDg3WuLw8UifO5TGCHbSo
