### ISSUE TITLE
Track down possible lost commits after git rebase

### ISSUE THREAD

**Issue by manekinekko** [angular/angular-fr#62]
Track down any possible lost commits after git rebase. Those are merged PR. 
Check each line if the related commit is present on [master](https://github.com/angular/angular-fr/tree/master):
- [x] 92fcb7e : chore: ability to toggle the english language #41
- [x] 142a48f : docs(glossary): french translation (a to c) #42
- [x] b82593c : docs(tutorial): french translation (_datas, index, pt1, pt2) #45
- [x] e2f23ba : docs(guide): french translation (typescript-configuration) #49
- [x] 6c3b85a : Component styles#15 #50
- [x] 4a4fc42 : docs(guide): french translation (animations) #52
- [x] ec52529 : docs(guide): french translation (webpack) #56
- [x] 4f96aec : docs(glossary): french translation (d to e) #61
- [x] 4f96aec : docs(glossary): french translation (d to e) #57
- [x] 71ce590 : docs(translation): fix typos in french Webpack section #58
